<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>4e32f96b-d870-4f39-8d54-da9c38998409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitOmset</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitOmset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b1d5623-c6be-4b68-a6e6-984c2cc1e8d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ad87310e-4215-4ac3-8387-47b76f743197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg</value>
      <webElementGuid>d7887588-e0ff-48c4-9b2d-6c4a5989f1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>2a330f61-8c00-42a6-9784-32006f531b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#loading</value>
      <webElementGuid>77ce9be9-5496-4e7a-a468-6d753445aac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitOmset</value>
      <webElementGuid>f32ee262-c608-49a7-8f4e-14f2d8159ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Submit
                                                </value>
      <webElementGuid>f18dbd2f-2850-417a-b3f3-0f003c6aaa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitOmset&quot;)</value>
      <webElementGuid>69bcb5d0-90b2-4d7f-891c-399218156926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitOmset']</value>
      <webElementGuid>a331a12f-c91a-46c5-8aa4-20107cd0ac3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan Akhir'])[1]/following::button[1]</value>
      <webElementGuid>3f8aef81-586b-4bbe-915a-f95675548e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf!, Anda belum memilih Nama Brand!'])[1]/preceding::button[2]</value>
      <webElementGuid>eb55ce39-b2cd-4067-bd5b-456e799768c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maaf!, Anda Tidak diperkenankan untuk memilih bulan ini!'])[1]/preceding::button[2]</value>
      <webElementGuid>06b5aedb-71e3-4fe9-8b22-aea920897dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>492775ad-435e-4fab-bdc4-d1f4f40d5856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>ac736f8e-0c31-41d8-ad2c-e41898580282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'submitOmset' and (text() = '
                                                    Submit
                                                ' or . = '
                                                    Submit
                                                ')]</value>
      <webElementGuid>2ac2b457-dbff-4bc5-a901-033f541d37c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
