<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Bulan                         _05b806</name>
   <tag></tag>
   <elementGuidId>7d78d97c-42aa-4775-82bb-b54106906bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visitation_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visitation_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a57f5ff-e6a1-4034-9ceb-8921a5355e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>d77b0df5-773e-4137-9a74-682d71b91bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visitation_month</value>
      <webElementGuid>3641a1f0-f4c2-4e13-969b-99fdffafd083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e6519b39-17a6-4097-aa72-7049533b0ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Pilih Bulan
                                                January
                                                February
                                                Maret
                                                April
                                                Mei
                                                Juni
                                                July
                                                Agustus
                                                September
                                                Oktober
                                                Nopember
                                                Desember
                                                </value>
      <webElementGuid>1f1b4c15-c696-47ff-b4d9-21d9102e8b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visitation_month&quot;)</value>
      <webElementGuid>a3a18759-745c-437d-a0f5-7532a737664e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visitation_month']</value>
      <webElementGuid>1e45da3b-1559-436c-a459-90ac283776d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFilter']/div/form/div/div[2]/div/select</value>
      <webElementGuid>330ba2cf-395e-4932-a1f8-3f4030f61eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Kunjungan RSM dan ASM'])[1]/following::select[2]</value>
      <webElementGuid>7943c8dd-c6a3-4378-a7f4-349163fa887d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterlambatan Trainer'])[1]/following::select[2]</value>
      <webElementGuid>a91b35a8-4a9f-451e-b342-cfe5b95e2f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[5]</value>
      <webElementGuid>68e2949f-838f-41ec-8f14-c905a7ae8232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rangkuman Kunjungan'])[1]/preceding::select[5]</value>
      <webElementGuid>b206dd91-fef0-4f4b-b234-778eb930afe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>cc7a20e2-6632-46db-afe7-ac59fcd6b13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'month' and @id = 'visitation_month' and (text() = '
                                                Pilih Bulan
                                                January
                                                February
                                                Maret
                                                April
                                                Mei
                                                Juni
                                                July
                                                Agustus
                                                September
                                                Oktober
                                                Nopember
                                                Desember
                                                ' or . = '
                                                Pilih Bulan
                                                January
                                                February
                                                Maret
                                                April
                                                Mei
                                                Juni
                                                July
                                                Agustus
                                                September
                                                Oktober
                                                Nopember
                                                Desember
                                                ')]</value>
      <webElementGuid>e6bccfe1-affe-46dd-aed5-c8625d7b9081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
