<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Bulan                         _05b806 (1)</name>
   <tag></tag>
   <elementGuidId>fe80ec0c-3f98-4ab2-96a5-c35ba1504319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visitation_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visitation_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d77277c-646d-4d48-918d-16e14c162d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>3ac851e7-68a5-4f40-9f61-36410c01d84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visitation_month</value>
      <webElementGuid>95d08a5c-25b8-4142-b426-814a17660c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3175d4d8-d8c1-4c44-9906-2dc0e2dd66de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Pilih Bulan
                                                January
                                                February
                                                Maret
                                                April
                                                Mei
                                                Juni
                                                July
                                                Agustus
                                                September
                                                Oktober
                                                Nopember
                                                Desember
                                                </value>
      <webElementGuid>73509c77-6511-402c-a4c7-5e8272c1a407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visitation_month&quot;)</value>
      <webElementGuid>ff5a648c-41a9-448e-a643-d5d1dfb30bdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visitation_month']</value>
      <webElementGuid>fb900576-7846-4d4e-9e84-1a6c817468a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFilter']/div/form/div/div[2]/div/select</value>
      <webElementGuid>1a5607a7-5449-4c4d-987e-1112cba19313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Kunjungan RSM dan ASM'])[1]/following::select[2]</value>
      <webElementGuid>30c60c21-ed5e-4047-aba9-0eaead3dc42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kunjungan RSM, ASM DBC'])[1]/following::select[2]</value>
      <webElementGuid>c00666b2-b400-450f-9931-75de1c01a7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[2]</value>
      <webElementGuid>d14cbe0a-c776-45ca-9dda-dfa8be6f3077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rangkuman Kunjungan'])[1]/preceding::select[2]</value>
      <webElementGuid>fd78417b-10bf-47f3-ae08-9d778a5f8ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>affce9d4-b961-40fa-b356-e2fd5edebfce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'month' and @id = 'visitation_month' and (text() = '
                                                Pilih Bulan
                                                January
                                                February
                                                Maret
                                                April
                                                Mei
                                                Juni
                                                July
                                                Agustus
                                                September
                                                Oktober
                                                Nopember
                                                Desember
                                                ' or . = '
                                                Pilih Bulan
                                                January
                                                February
                                                Maret
                                                April
                                                Mei
                                                Juni
                                                July
                                                Agustus
                                                September
                                                Oktober
                                                Nopember
                                                Desember
                                                ')]</value>
      <webElementGuid>306e449f-6823-4bb0-9eb5-45c5acac2fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
