<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Tahun                         _25cfb8 (1)</name>
   <tag></tag>
   <elementGuidId>39fdebd0-af7c-4e54-947f-37b428e908a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visitation_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visitation_year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>793a4f3f-5e6d-4e6f-89cb-cd20dbdc4d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>5c3d5144-586f-407f-9a19-615085f6e084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visitation_year</value>
      <webElementGuid>6cf313f4-2e91-4b83-91fd-4a2987761f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2b84437-8963-4a6b-8461-7e765853cfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Tahun
                                                    2019
                                                    2020
                                                    2021
                                                    2022
                                                </value>
      <webElementGuid>4b3fdae2-deb5-465e-9ed7-dc147557199f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visitation_year&quot;)</value>
      <webElementGuid>e5e635bf-785f-4a84-9f99-49574879b89a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visitation_year']</value>
      <webElementGuid>fdded14e-2a3b-447a-9701-2fd059e854be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFilter']/div/form/div/div/div/select</value>
      <webElementGuid>a8c14878-6612-49dd-98d0-83e8cf2becf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Kunjungan RSM dan ASM'])[1]/following::select[1]</value>
      <webElementGuid>b5dd3179-59cf-4241-a5a2-69ae8d1929b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kunjungan RSM, ASM DBC'])[1]/following::select[1]</value>
      <webElementGuid>eced16e7-e113-4dbc-866e-49a7d288d93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[3]</value>
      <webElementGuid>1d2662f7-fe9f-4e26-aa76-ab2a3b6e5f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rangkuman Kunjungan'])[1]/preceding::select[3]</value>
      <webElementGuid>6922e7d0-1f5a-4b90-a9d7-46b7a553a933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>334a95a5-71a6-423a-804f-26b7b54fedc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'year' and @id = 'visitation_year' and (text() = '
                                                    Pilih Tahun
                                                    2019
                                                    2020
                                                    2021
                                                    2022
                                                ' or . = '
                                                    Pilih Tahun
                                                    2019
                                                    2020
                                                    2021
                                                    2022
                                                ')]</value>
      <webElementGuid>4a109415-b956-432c-b030-7730a37b3800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
