<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Tahun                         _25cfb8</name>
   <tag></tag>
   <elementGuidId>9288566a-e2db-488f-8108-17091194e00a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='visitation_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visitation_year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f18f618-5da7-4ec2-923a-5650de04d8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>982253cb-d9d0-4aba-9453-a96beed01473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visitation_year</value>
      <webElementGuid>01409f81-5768-4234-bbad-15921b96d2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>255c46c2-294a-401a-9247-4298d15a6e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Pilih Tahun
                                                    2019
                                                    2020
                                                    2021
                                                    2022
                                                </value>
      <webElementGuid>eac55306-98d8-4277-953d-f6e1e3be6c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visitation_year&quot;)</value>
      <webElementGuid>d570aac3-97ba-4aa1-ac7f-4dd39433eb8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='visitation_year']</value>
      <webElementGuid>8603cf84-427e-4628-983d-8c3cfca42109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFilter']/div/form/div/div/div/select</value>
      <webElementGuid>d66a54e5-c327-4b40-af28-038d9c3d4231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Kunjungan RSM dan ASM'])[1]/following::select[1]</value>
      <webElementGuid>4fade522-75f4-4c6d-9904-0ca005d5af96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterlambatan Trainer'])[1]/following::select[1]</value>
      <webElementGuid>de1a95ec-f718-420d-a11f-d5dc8b25dec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[6]</value>
      <webElementGuid>34ae7b6b-da69-4b2d-9e80-5fc38bfc992e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rangkuman Kunjungan'])[1]/preceding::select[6]</value>
      <webElementGuid>f99780a8-7356-4d0f-855e-ae5e62599d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>84c45d29-c8c8-4229-ac5f-99cb8d1a702c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'year' and @id = 'visitation_year' and (text() = '
                                                    Pilih Tahun
                                                    2019
                                                    2020
                                                    2021
                                                    2022
                                                ' or . = '
                                                    Pilih Tahun
                                                    2019
                                                    2020
                                                    2021
                                                    2022
                                                ')]</value>
      <webElementGuid>8d415493-ef85-4317-949f-602c935e79f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
