<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Dashboard_h-8 w-8 rounded-full object-cover (1)</name>
   <tag></tag>
   <elementGuidId>6623a80d-3474-406e-b91e-51154c0c75f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-8.w-8.rounded-full.object-cover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Tsabit Rakhman']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a174ead-dc08-4183-bdc4-b5524c184b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-8 w-8 rounded-full object-cover</value>
      <webElementGuid>1e5158ce-64c7-41eb-83a8-a10b1730ef9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://noncore-assets.s3.ap-southeast-1.amazonaws.com/system-admin-service/prd/assets/img/tsabit@dbo.id-1657598771.jpeg</value>
      <webElementGuid>f5aa1618-ab7a-45b7-95ec-99d4d3df6f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://ui-avatars.com/api/?name=&amp;color=7F9CF5&amp;background=EBF4FF';</value>
      <webElementGuid>8043c7db-c301-4a54-8208-c43514b1bd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tsabit Rakhman</value>
      <webElementGuid>e907f4a2-5d68-47e2-af8d-b54a1b744dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;font-sans antialiased&quot;]/div[@class=&quot;min-h-screen bg-gray-100&quot;]/nav[@class=&quot;bg-white border-b border-gray-100&quot;]/div[@class=&quot;max-w-7xl mx-auto px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex justify-between h-16&quot;]/div[@class=&quot;hidden sm:flex sm:items-center sm:ml-6&quot;]/div[@class=&quot;relative&quot;]/div[1]/button[@class=&quot;flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out&quot;]/img[@class=&quot;h-8 w-8 rounded-full object-cover&quot;]</value>
      <webElementGuid>9df6db72-8692-409f-a21a-570f438a2e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tsabit Rakhman']</value>
      <webElementGuid>126e1650-7b42-456b-b682-b29d3d55c5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>d30f14a6-37e2-40b7-95c3-5dd03dccae4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://noncore-assets.s3.ap-southeast-1.amazonaws.com/system-admin-service/prd/assets/img/tsabit@dbo.id-1657598771.jpeg' and @alt = 'Tsabit Rakhman']</value>
      <webElementGuid>83fb82a5-00a4-4146-bbaa-8d2f060844a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
