<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Dashboard_h-8 w-8 rounded-full object-cover</name>
   <tag></tag>
   <elementGuidId>9c50d88b-af1c-44ba-8672-607893720e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Tsabit Rakhman']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.h-8.w-8.rounded-full.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>364afd88-372b-415e-91d2-ef4390dac618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-8 w-8 rounded-full object-cover</value>
      <webElementGuid>5a7599a6-1394-4b84-bee3-cd1d9939f15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://noncore-assets.s3.ap-southeast-1.amazonaws.com/system-admin-service/prd/assets/img/tsabit@dbo.id-1657598771.jpeg</value>
      <webElementGuid>c1ba94df-a73f-4d91-b7cf-d86c411028b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://ui-avatars.com/api/?name=&amp;color=7F9CF5&amp;background=EBF4FF';</value>
      <webElementGuid>2bbdf711-6249-495d-a8f9-5285a12fd8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tsabit Rakhman</value>
      <webElementGuid>22b87d04-bbe2-49d6-a6e8-703e0ee34df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;font-sans antialiased&quot;]/div[@class=&quot;min-h-screen bg-gray-100&quot;]/nav[@class=&quot;bg-white border-b border-gray-100&quot;]/div[@class=&quot;max-w-7xl mx-auto px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;flex justify-between h-16&quot;]/div[@class=&quot;hidden sm:flex sm:items-center sm:ml-6&quot;]/div[@class=&quot;relative&quot;]/div[1]/button[@class=&quot;flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out&quot;]/img[@class=&quot;h-8 w-8 rounded-full object-cover&quot;]</value>
      <webElementGuid>3b224a86-1928-4141-a5e1-01de03827e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tsabit Rakhman']</value>
      <webElementGuid>b1de003d-dcba-49e4-b0a4-8e87975060f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>38d8a475-d99b-402f-86b8-4f20b80a3466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://noncore-assets.s3.ap-southeast-1.amazonaws.com/system-admin-service/prd/assets/img/tsabit@dbo.id-1657598771.jpeg' and @alt = 'Tsabit Rakhman']</value>
      <webElementGuid>b5a718d2-6f07-4c64-bf9d-4f1e46a83f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
